### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by corrinavatan** [th3proj3ct/wh40k-apocalypse-10e#13]
link in instructions ( https://github.com/th3proj3ct/wh40k-apocalypse-10e/releases/download/Release/index.bsi) returns a 404 file not found in browser, and missing file errors in Battlescribe

**Comment by corrinavatan** [comment]
error encountered trying to use file in battlescribe:

Details:

Failed to download from one or more repositories

1) https://github.com/th3proj3ct/wh40k-apocalypse-10e/releases/download/Release/index.bsi
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.a(BattleScribe:525)
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.call(BattleScribe:481)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by th3proj3ct** [comment]
Also this is now meant to be used solely in NewRecruit using hte latest commit as the option
